server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  boot:
    admin:
      client:
        instance:
          management-base-url: http://localhost:9092
#  boot:
#    admin:
#      client:
#        url:
#          - http://localhost:9898

management:
  endpoints:
    web:
      exposure:
        include: "*"